server:
  port: 8001
spring:
  profiles:
    - dev
  application:
    name: skeleton-service
  cloud:
    config:
      uri: http://localhost:8888
  security:
    user:
      password: P@ssword1
      name: user
      roles:
        - USER, ENDPOINT_ADMIN
    basic:
      enabled: false
  datasource:
      url: jdbc:h2:file:E:/_CodeRepo/skeleton-service
      driverClassName: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  file:
    name: E://springbootLogs//skeleton-service.log
  level:
    - DEBUG

management:
  endpoints:
    web:
#      base-path: /devops/actuator
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
info:
  team:
    name: INFO TEXT
    dev: Amol Bhople
    verison: 1.0.0
    project:
      owner: Amol Bhople




---
#TEST properties................................
server:
  port: 9001
spring:
  profiles:
    - test
  application:
    name: skeleton-service
  cloud:
    config:
      uri: http://localhost:9999